export const loginApi = 'login'
export const shopListApi = 'auth/role-wise-shop'
export const signUpApi = 'signup'
// export const authUserRolesApi = '/auth/user-roles'
// export const componentsByRoleApi = '/auth/components-by-role'
// export const componentsOfSuperAdminApi = '/menu/components-from-menu'
export const sidebarMenusApi = '/auth/sidebar-menus'
