const division = '/address/division/'
export const divisionList = division + 'list'
export const divisionUpdate = division + 'update'
export const divisionStore = division + 'store'
export const divisionToggle = division + 'toggle-status'
// District List Routes ...
const district = '/address/district/'
export const districtList = district + 'list'
export const districtUpdate = district + 'update'
export const districtStore = district + 'store'
export const districtToggle = district + 'toggle-status'
// Upazila List Routes ...
const upazila = '/address/upazilla/'
export const upazilaList = upazila + 'list'
export const upazilaUpdate = upazila + 'update'
export const upazilaStore = upazila + 'store'
export const upazilaToggle = upazila + 'toggle-status'
// Paurashava List Routes ...
const pauroshava = '/address/pauroshova/'
export const pauroshavaList = pauroshava + 'list'
export const pauroshavaUpdate = pauroshava + 'update'
export const pauroshavaStore = pauroshava + 'store'
export const pauroshavaToggle = pauroshava + 'toggle-status'
// Union List Routes ...
const union = '/address/union/'
export const unionList = union + 'list'
export const unionUpdate = union + 'update'
export const unionStore = union + 'store'
export const unionToggle = union + 'toggle-status'
// ward List Routes ...
const ward = '/address/ward/'
export const wardList = ward + 'list'
export const wardUpdate = ward + 'update'
export const wardStore = ward + 'store'
export const wardToggle = ward + 'toggle-status'
// Bank List Routes ...
const bank = '/address/bank/'
export const bankList = bank + 'list'
export const bankUpdate = bank + 'update'
export const bankStore = bank + 'store'
export const bankToggle = bank + 'toggle-status'
// Branch List Routes ...
const branch = '/address/branch/'
export const branchList = branch + 'list'
export const branchUpdate = branch + 'update'
export const branchStore = branch + 'store'
export const branchToggle = branch + 'toggle-status'
// Shop Management List Routes ...
const shopEntry = '/shop-management/shop/'
export const shopEntryList = shopEntry + 'list'
export const shopEntryUpdate = shopEntry + 'update'
export const shopEntryStore = shopEntry + 'store'
export const shopEntryToggle = shopEntry + 'toggle-status'
