const division = '/address/division/'
export const divisionList = division + 'list'
export const divisionUpdate = division + 'update'
export const divisionStore = division + 'store'
export const divisionToggle = division + 'toggle-status'
// District Routes ...
const district = '/address/district/'
export const districtList = district + 'list'
export const districtUpdate = district + 'update'
export const districtStore = district + 'store'
export const districtToggle = district + 'toggle-status'
// Upazila Routes ...
const upazila = '/address/upazilla/'
export const upazilaList = upazila + 'list'
export const upazilaUpdate = upazila + 'update'
export const upazilaStore = upazila + 'store'
export const upazilaToggle = upazila + 'toggle-status'
// Paurashava Routes ...
const pauroshava = '/address/pauroshova/'
export const pauroshavaList = pauroshava + 'list'
export const pauroshavaUpdate = pauroshava + 'update'
export const pauroshavaStore = pauroshava + 'store'
export const pauroshavaToggle = pauroshava + 'toggle-status'
// Union  Routes ...
const union = '/address/union/'
export const unionList = union + 'list'
export const unionUpdate = union + 'update'
export const unionStore = union + 'store'
export const unionToggle = union + 'toggle-status'
// ward Routes ...
const ward = '/address/ward/'
export const wardList = ward + 'list'
export const wardUpdate = ward + 'update'
export const wardStore = ward + 'store'
export const wardToggle = ward + 'toggle-status'
// Bank Routes ...
const bank = '/address/bank/'
export const bankList = bank + 'list'
export const bankUpdate = bank + 'update'
export const bankStore = bank + 'store'
export const bankToggle = bank + 'toggle-status'
// Branch Routes ...
const branch = '/address/branch/'
export const branchList = branch + 'list'
export const branchUpdate = branch + 'update'
export const branchStore = branch + 'store'
export const branchToggle = branch + 'toggle-status'
// City Corporation Routes ...
const cityCorporation = '/address/cityCorporation/'
export const cityCorporationList = cityCorporation + 'list'
export const cityCorporationUpdate = cityCorporation + 'update'
export const cityCorporationStore = cityCorporation + 'store'
export const cityCorporationToggle = cityCorporation + 'toggle-status'
