const category = '/product-management/category/'
export const categoryList = category + 'list'
export const categoryStore = category + 'store'
export const categoryUpdate = category + 'update'
export const categoryToggle = category + 'toggle-status'
// Brand Routes...
const brand = '/product-management/brand/'
export const brandList = brand + 'list'
export const brandStore = brand + 'store'
export const brandUpdate = brand + 'update'
export const brandToggle = brand + 'toggle-status'
// Color Routes...
const color = '/product-management/color/'
export const colorList = color + 'list'
export const colorStore = color + 'store'
export const colorUpdate = color + 'update'
export const colorToggle = color + 'toggle-status'
// Model Routes...
const model = '/product-management/model/'
export const modelList = model + 'list'
export const modelStore = model + 'store'
export const modelUpdate = model + 'update'
export const modelToggle = model + 'toggle-status'
// Size Routes...
const size = '/product-management/size/'
export const sizeList = size + 'list'
export const sizeStore = size + 'store'
export const sizeUpdate = size + 'update'
export const sizeToggle = size + 'toggle-status'
